### ISSUE TITLE
Lernübung Umwandlung zwischen paralleler und serieller Impedanz  

### ISSUE THREAD

**Issue by loneoma1** [mojodo/EL2-stud#2]
![ParallelZuSeriell](https://user-images.githubusercontent.com/63157891/78461003-0c4a0080-76c6-11ea-8ae4-06a0dfee1d22.PNG)
Sehr geehrter Herr mojodo

Zur Lernübung: Aus dem MatLab Skript erhalten wir folgende Figur, siehe Anhang.
Könnten Sie bitte erläutern, wieso der Imaginäre-Teil am Anfang zunimmt und danach wieder ab. 
Hat der Grund auch wieder mit der zunehmender Winkelgeschwindigkeit zu tun?
Für die parallele Impedanz erhalten etwas der Form: A/B +j*C/B und für den Imaginär-Teil haben wir: R2^2*X2/(R2^2+X2^2).  Meine Überlegung ist, dass zu Beginn der Nenner grösser ist als der Zähler und dann ab einer bestimmen Frequenz es gerade kippt, so dass der Nenner > Zähler ist. 

Vielen Dank für Ihre Zeit und Hilfe.

Freundliche Grüsse
Omar

**Comment by mojodo** [comment]
guten Tag Herr Leoneoma1

ja, so ist es hier alles nochmals ganz einfach.

1/(1+j*omega) = 1/(1+omega^2)  - j*omega/(1+omega^2)
Wir beobachten, mit von null anwachsendem omegea nimmt der Realteil dieser Zahl ab. Der Imaginärteil nimmt zuerst zu und dann ab. Er nimmt zuerst zu weil bei kleinen omega die 1 dominiert. Irgendwann dominiert omega^2 und damit nimmt der Imaginärteil mit etwa 1/omega ab.

Freundliche Grüsse
mojdodo
